### ISSUE TITLE
Add CI/CD tests

### ISSUE THREAD

**Issue by kassane** [batiati/tigerbeetle-clients-benchmarks#2]
Hi @batiati,

Do you want to add tests to the GH actions?

I don't know if they've fixed the problem with `run_with_tb`. However, I'm already working on an alternative solution to make the tests better available on the CI/CD.
- https://github.com/tigerbeetle/tigerbeetle/issues/794

And also present a "jabá" (propaganda) about cmake in C and/or C++ tb_projects.
**[WIP]:** https://github.com/batiati/tigerbeetle-clients-benchmarks/compare/master...kassane:tigerbeetle-clients-benchmarks:upstream

**Comment by batiati** [comment]
Having a CI cron job to check if our benchmarks are up-to-date is really cool!

However, it would be essential to remove the TigerBeetle submodule and clone a fresh repo from `main` every time the CI runs as it is the dependency that changes more often.

**Comment by kassane** [comment]
> However, it would be essential to remove the TigerBeetle submodule and clone a fresh repo from `main` every time the CI runs as it is the dependency that changes more often.

I removed the git submodule in the suggested PR.
Like this?
https://github.com/batiati/tigerbeetle-clients-benchmarks/blob/73e7c63eb5ec41cfdc36aa9c989f2777f0c6c72d/scripts/install.sh#L4-L6

**Comment by batiati** [comment]
Yes, awesome!
